# image will be published to ghcr.io/<user>/<name>
name: nightwing
# description will be included in the image's metadata
description: A custom image containing the goto applications and files.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README
      - etc: /etc

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://raw.githubusercontent.com/dgmann/nightwing/live/config/rpm-ostree/netbird.repo
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      # - micro
      # - starship
      - kitty
      - libadwaita
      - fish
      - powerline-fonts
      - kvantum
      - code
      # Netbird + Dependencies
      - netbird
      # Docker
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      # Misc
      - sunshine
      - thefuck
    remove:
      - tailscale
      #- firefox # default firefox removed in favor of flatpak
      #- firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: systemd
    system:
      enabled:
        - sunshine-workaround.service

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update
      # - 1password # install 1Password (stable) and `op` CLI tool
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - gnome-vrr # enables gnome-vrr for your image
      # - laptop # installs TLP and configures your system for laptop usage
      # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add "Nerd Font" suffix.

  #- type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
  #              #  will be installed and set up
  #  custom-flatpaks: # this section is optional
  #    # - Celluloid: io.github.celluloid_player.Celluloid
  #    # - Krita: org.kde.krita

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
